apiVersion: v1
kind: PersistentVolume
metadata:
  name: mp3-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/storage/mp3s
    server: 10.0.0.60
  persistentVolumeReclaimPolicy: Retain
